### ISSUE TITLE
QA for Close Pull Request When Unassigned

### ISSUE THREAD

**Issue by Draeieg** [ubiquibot/staging#38]
Testing PR [400](https://github.com/ubiquity/ubiquibot/pull/400)

**Comment by ubiquity-bounties** [comment]
Permit generation skipped because assignee is `undefined`.

###### If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!

---

We should consolidate the promotional comment into the permit generation comment.
