### ISSUE TITLE
QA for Html comments

### ISSUE THREAD

**Issue by Draeieg** [ubiquibot/staging#87]
testing PR [545](https://github.com/ubiquity/ubiquibot/pull/545)

**Comment by devtestubq** [comment]
Describe the background or context

![R](https://github.com/ubiquibot/staging/assets/124931263/efd58805-dbf9-4b40-a08f-4ec3e051011b)

Describe the solution
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

- Lorem Ipsum
- dummy text
- industry's standard

**Comment by Draeieg** [comment]
Describe the background or context
No response

Describe the solution
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

- Lorem Ipsum
- dummy text
- industry's standard
